BOARD_TAG = mega2560
MCU = atmega2560
ARDUINO_PORT = /dev/ttyACM0

ARDUINO_LIBS = ros_lib ros_lib/ros ros_lib/std_msgs I2Cdev MPU6050 Wire ros_lib/arduino_msgs Wire/utility

include /usr/share/arduino/Arduino.mk
