




.build/mega2560/src/OpenROV.cpp : src/OpenROV.ino
	@mkdir -p .build/mega2560/src
	@echo [93msrc/OpenROV.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/mega2560/src/OpenROV.cpp
	@true

